
export const ACTION_SELECT_SUBPRODUCT = "product.ACTION_SELECT_SUBPRODUCT";
export const ACTION_SELECT_COLOR = "product.ACTION_SELECT_COLOR";
export const ACTION_ADD_PRODUCT_TO_CART = "cart.ACTION_ADD_PRODUCT_TO_CART";
